### ISSUE TITLE
Wrong prefix definition in mappings

### ISSUE THREAD

**Issue by paoespinozarias** [oeg-upm/drugs4covid19-kg#1]
d4covid: https://w3id.org/def/DRUGS4COVID19/ should be d4covid: https://w3id.org/def/DRUGS4COVID19# (in order to be consistent with the [ontology](https://w3id.org/def/DRUGS4COVID19))

**Comment by dachafra** [comment]
only for the predicates

**Comment by dachafra** [comment]
solved!
